#########################################
#                                       #
#       这里是BBSToper的配置文件        #
#                                       #
#########################################

#项目地址: https://github.com/R-Josef/BBSToper
#MCBBS下载地址: https://www.mcbbs.net/thread-789082-1-1.html
#请定期检查这些网址以获取可用的更新
#Copyright © 2018-2019 R_Josef 版权所有

#数据库设置
database:
    #表名前缀, 在sqlite和mysql都有效
    #可用两个单引号表示留空, 例如prefix: ''
    prefix: 'bt_'
    #定时自动断开并重新连接数据库
    #数据库使用长连接有可能导致速度越来越慢(我不确定)
    #可以尝试开启此选项, 单位秒, 设置为0则关闭
    timingreconnect: 0
    #可选mysql或sqlite
    type: 'sqlite'
    #mysql设置
    mysql:
        ip: 'localhost'
        port: '3306'
        database: 'databasename'
        user: 'username'
        password: 'password'
        ssl: false
    #sqlite设置
    sqlite:
        folder: '%PLUGIN_FOLDER%'
        database: 'bbstoper.db'
    
mcbbs:
    #服务器宣传贴的帖子id
    url: '1034574'
    #顶帖列表/玩家排名每页的大小
    pagesize: 10
    #玩家多久能更换一次绑定的id, 单位天
    changeidcooldown: 30
    #如果一个玩家没有顶贴是否在加入时发送提示消息
    joinmessage: true
    
gui:
    #玩家排名的显示数量
    topplayers: 5
    #显示GUI中的头颅皮肤
    #获取头颅皮肤时有可能因为网络原因造成卡顿(我不确定)
    #如果在打开GUI时遇到主线程卡顿, 请尝试关闭此项
    displayheadskin: true
    #是否启用按键后输入绑定ID
    #如果某些插件导致玩家聊天事件消息被修改或者取消
    #那么插件将获取不到正确的输入，这时候请关闭此项
    usechatgetid: true

#奖励设置
reward:
    #自动奖励间隔，将在指定的间隔下循环访问宣传帖
    #如有玩家顶贴就将自动给该玩家奖励，但必须该玩家在线
    #单位秒，设置为0则关闭，此选项需要大量网络IO建议设置为30左右
    auto: 30
    #顶贴后领取奖励的有效期, 单位天
    period: 10
    #一天能领取几次顶帖奖励
    times: 1
    #奖励的命令, %PLAYER%代表使用命令的玩家ID
    commands:
    - 'experience add %PLAYER% 1000'
    - 'eco give %PLAYER% 20'